### PR TITLE
Icon theme support

### PR DESCRIPTION
**Pull request by bionade24**
This PR adds support for icon themes and makes the previously used icon set an icon theme which is included in the binary, acting as fallback if the icon theme set by the user is not available or lacks the needed icons.
Due to some QT iternals, the icons folder has to be part for the path of the files referenced in the `.qrc` files for Qt to recognize the icon system.

If you prefer so, I could move `icons.qrc` and `icons` into a folder, e.g. `res`. But using `/icons` as a QRC prefix doesn't work.

This PR also adds cmake code to set a a build type if none was specified and sets `QT_NO_DEBUG_OUTPUT` on non-debug builds.

If have not touched the existing unused icons, they may should be removed.

### CODE REVIEW

**Comment by bionade24** [comment]
I just noticed today while working on cursor hide that I used spaces instead of tabs.  Please give me some time to fix it.

**Comment by brainrom** [comment]
This is the real correct way of handling QIcon themes, I was looking for. Icons directory in root is ok.

But please correct these things before merge:
1. .ts files shouldn't be ignored. Translations will be added in the future.
2. Remove CMAKE_EXPORT_COMPILE_COMMANDS, it shouldn't be needed in the usual case.
3. Theme name should be in config file and set via setThemeName() during startup, `kokovp-default` should be default value.

**Comment by bionade24** [comment]
I noticed that some files use 4 spaces and some use tabs. What is your preference? May you please add a clang-format.yml to the project?

> .ts files shouldn't be ignored. Translations will be added in the future.

My mistake, should've known they usually don't get autogenerated.

> Theme name should be in config file and set via setThemeName() during startup, kokovp-default should be default value.

I very much disagree with this. Applications should respect the system (icon) themes and default to them. The config option in the settings should default to this and provide an option to ignore the system theming. A GNOME user expects applications to use Adwaita or their global settings, a KDE user breeze or global settings, a user who has specified QT_QPA_PLATFORMTHEME its setting.

**Comment by brainrom** [comment]
> Applications should respect the system (icon) themes and default to them.

I agree with this, but my motivation was at keeping current behavior, until proper configuration GUI will be implemented. As a half-measure I added config option for this, but not GUI.

Merged, thank you again!

**Pull request merged**
